// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview AI-powered tool that suggests relevant expertise tags based on a mentor's entered skills.
 *
 * - generateProfileTags - A function that generates expertise tags for mentor profiles.
 * - GenerateProfileTagsInput - The input type for the generateProfileTags function.
 * - GenerateProfileTagsOutput - The return type for the generateProfileTags function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateProfileTagsInputSchema = z.object({
  enteredSkills: z
    .string()
    .describe('A comma-separated list of skills entered by the mentor.'),
});
export type GenerateProfileTagsInput = z.infer<
  typeof GenerateProfileTagsInputSchema
>;

const GenerateProfileTagsOutputSchema = z.object({
  suggestedTags: z
    .array(z.string())
    .describe('An array of suggested expertise tags.'),
});
export type GenerateProfileTagsOutput = z.infer<
  typeof GenerateProfileTagsOutputSchema
>;

export async function generateProfileTags(
  input: GenerateProfileTagsInput
): Promise<GenerateProfileTagsOutput> {
  return generateProfileTagsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateProfileTagsPrompt',
  input: {schema: GenerateProfileTagsInputSchema},
  output: {schema: GenerateProfileTagsOutputSchema},
  prompt: `You are an expert in identifying relevant expertise tags for mentor profiles.

  Given the following skills entered by a mentor, suggest a list of tags that would enhance their searchability by mentees.

  Skills: {{{enteredSkills}}}

  Return the suggested tags as a JSON array of strings.
  `,
});

const generateProfileTagsFlow = ai.defineFlow(
  {
    name: 'generateProfileTagsFlow',
    inputSchema: GenerateProfileTagsInputSchema,
    outputSchema: GenerateProfileTagsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
